import { useEffect, useState } from "react";
import { Link, useRouter } from "expo-router";
import { Button, GlassCard, LoadingScreen, Screen, Text, TextField, theme } from "@shapers/ui";
import { createPurposeQuestion, getCurrentUser, getPurposeQuestions } from "@shapers/api-client";
import type { CurrentUser, PurposeAssessmentQuestion } from "@shapers/types";
import { getSupabaseClient } from "@/lib/supabase";
import { logoSource } from "@/lib/logo";

function weights(value: string): Record<string, number> { return Object.fromEntries(value.split(",").map((gift) => gift.trim().toLowerCase()).filter(Boolean).map((gift) => [gift, 1])); }

export default function AssessmentAdminScreen() {
  const router = useRouter(); const [me, setMe] = useState<CurrentUser | null>(null); const [questions, setQuestions] = useState<PurposeAssessmentQuestion[] | null>(null); const [question, setQuestion] = useState(""); const [options, setOptions] = useState(["", "", ""]); const [gifts, setGifts] = useState(["", "", ""]); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  async function load() { const client = getSupabaseClient(); const user = await getCurrentUser(client); if (!user) { router.replace("/onboarding/match"); return; } if (!user.roleAssignments.some((role) => role.role === "admin")) { router.replace("/dashboard"); return; } const items = await getPurposeQuestions(client); setMe(user); setQuestions(items); }
  useEffect(() => { void load().catch((err) => setError(err instanceof Error ? err.message : "Unable to load assessment questions.")).finally(() => setQuestions((value) => value ?? [])); }, []);
  async function submit() { if (!me) return; setSaving(true); setError(null); try { await createPurposeQuestion(getSupabaseClient(), { churchId: me.person.church_id, questionText: question, category: "spiritual_gift", options: options.map((text, index) => ({ key: String.fromCharCode(97 + index), text, weight: weights(gifts[index] ?? "") })) }); setQuestion(""); setOptions(["", "", ""]); setGifts(["", "", ""]); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to save question."); } finally { setSaving(false); } }
  if (!questions || !me) return <LoadingScreen logoSource={logoSource} />;
  const complete = Boolean(question.trim()) && options.every((option, index) => Boolean(option.trim()) && Object.keys(weights(gifts[index] ?? "")).length > 0);
  return <Screen logoSource={logoSource}><Link href="/admin" style={{ color: theme.color.textMuted, marginBottom: theme.spacing(4) }}>← Back to admin</Link><Text style={{ fontSize: 27, fontWeight: "700", marginBottom: 6 }}>Purpose assessment</Text><Text style={{ color: theme.color.textMuted, marginBottom: theme.spacing(6) }}>Add a question and map each answer to gift keys.</Text><TextField label="Question" value={question} onChangeText={setQuestion} />{options.map((option, index) => <GlassCard key={index} style={{ marginBottom: 10 }}><TextField label={`Option ${index + 1}`} value={option} onChangeText={(value) => setOptions(options.map((item, itemIndex) => itemIndex === index ? value : item))} /><TextField label="Gift keys, comma-separated" value={gifts[index] ?? ""} onChangeText={(value) => setGifts(gifts.map((item, itemIndex) => itemIndex === index ? value : item))} placeholder="teaching, leadership" /></GlassCard>)}{error ? <Text style={{ color: theme.color.danger, marginBottom: 10 }}>{error}</Text> : null}<Button title="Add question" loading={saving} disabled={!complete} onPress={submit} /><Text style={{ fontWeight: "700", marginTop: theme.spacing(7), marginBottom: 8 }}>Current questions</Text>{questions.length === 0 ? <Text style={{ color: theme.color.textMuted }}>No questions have been added yet.</Text> : questions.map((item) => <Text key={item.id} style={{ paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: theme.color.border }}>{item.question_text}</Text>)}</Screen>;
}
