import { useEffect, useState } from "react";
import { Link, useRouter } from "expo-router";
import { Button, GlassCard, LoadingScreen, Screen, Text, TextField, theme } from "@shapers/ui";
import { addGrowthTrackLesson, createGrowthTrackStage, getCourseWithLessons, getCurrentUser, getGrowthTrack } from "@shapers/api-client";
import type { CourseWithLessons, CurrentUser } from "@shapers/types";
import { getSupabaseClient } from "@/lib/supabase";
import { logoSource } from "@/lib/logo";

const stageNames = ["Purpose", "Pursuit", "Partner", "Produce"];

export default function GrowthTrackAdminScreen() {
  const router = useRouter(); const [me, setMe] = useState<CurrentUser | null>(null); const [stages, setStages] = useState<CourseWithLessons[] | null>(null); const [stageTitle, setStageTitle] = useState(""); const [firstLesson, setFirstLesson] = useState(""); const [lessonTitles, setLessonTitles] = useState<Record<string, string>>({}); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  async function load() { const client = getSupabaseClient(); const user = await getCurrentUser(client); if (!user) { router.replace("/onboarding/match"); return; } if (!user.roleAssignments.some((role) => role.role === "admin")) { router.replace("/dashboard"); return; } const courses = await getGrowthTrack(client); const details = await Promise.all(courses.map((course) => getCourseWithLessons(client, course.id))); setMe(user); setStages(details.filter((item): item is CourseWithLessons => item !== null)); }
  useEffect(() => { void load().catch((err) => setError(err instanceof Error ? err.message : "Unable to load Growth Track.")).finally(() => setStages((value) => value ?? [])); }, []);
  async function addStage() { if (!stages) return; setSaving(true); setError(null); try { const position = [1, 2, 3, 4].find((value) => !stages.some((stage) => stage.course.position === value)); if (!position) throw new Error("All four stages already exist."); const defaultTitle = stageNames[position - 1]; if (!defaultTitle) throw new Error("Invalid Growth Track position."); await createGrowthTrackStage(getSupabaseClient(), { title: stageTitle || defaultTitle, position, firstLessonTitle: firstLesson }); setStageTitle(""); setFirstLesson(""); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to create stage."); } finally { setSaving(false); } }
  async function addLesson(courseId: string) { const title = lessonTitles[courseId]?.trim(); if (!title) { setError("Enter a lesson title first."); return; } setSaving(true); setError(null); try { await addGrowthTrackLesson(getSupabaseClient(), { courseId, title }); setLessonTitles({ ...lessonTitles, [courseId]: "" }); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to add lesson."); } finally { setSaving(false); } }
  if (!stages || !me) return <LoadingScreen logoSource={logoSource} />;
  const nextPosition = [1, 2, 3, 4].find((value) => !stages.some((stage) => stage.course.position === value));
  return <Screen logoSource={logoSource}><Link href="/admin" style={{ color: theme.color.textMuted, marginBottom: theme.spacing(4) }}>← Back to admin</Link><Text style={{ fontSize: 27, fontWeight: "700", marginBottom: 6 }}>Growth Track</Text><Text style={{ color: theme.color.textMuted, marginBottom: theme.spacing(6) }}>Build stages and their real lessons.</Text>{error ? <Text style={{ color: theme.color.danger, marginBottom: 10 }}>{error}</Text> : null}{nextPosition ? <GlassCard style={{ marginBottom: theme.spacing(5) }}><Text style={{ fontWeight: "700", marginBottom: 8 }}>Add stage {nextPosition}: {stageNames[nextPosition - 1]}</Text><TextField label="Stage title" value={stageTitle} onChangeText={setStageTitle} placeholder={stageNames[nextPosition - 1]} /><TextField label="First lesson title" value={firstLesson} onChangeText={setFirstLesson} /><Button title="Create stage" loading={saving} disabled={!firstLesson.trim()} onPress={addStage} /></GlassCard> : null}{stages.map((stage) => <GlassCard key={stage.course.id} style={{ marginBottom: theme.spacing(4) }}><Text style={{ color: theme.color.textMuted, fontSize: 12, marginBottom: 4 }}>STAGE {stage.course.position}</Text><Text style={{ fontWeight: "700", fontSize: 18, marginBottom: 8 }}>{stage.course.title}</Text>{stage.lessons.map((lesson) => <Text key={lesson.id} style={{ color: theme.color.textMuted }}>{lesson.position}. {lesson.title}</Text>)}<TextField label="New lesson title" value={lessonTitles[stage.course.id] ?? ""} onChangeText={(value) => setLessonTitles({ ...lessonTitles, [stage.course.id]: value })} /><Button title="Add lesson" variant="secondary" loading={saving} onPress={() => addLesson(stage.course.id)} /></GlassCard>)}</Screen>;
}
